[package]
name = "api"
version = "0.1.0"

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.4", features = ["macros"] }
image = { version = "0.24.8", features = [] }
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
reqwest = { version = "0.11.24", default-features = false, features = [
    "rustls",
    "json",
    "rustls-tls",
] }
rayon = "1.8.1"
futures = "0.3.30"
axum_thiserror = "0.1.0"
serde = { version = "1.0.196", features = ["derive"] }
blurslice = "0.1.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
lazy_static = "1.5.0"
ffmpeg-next = "7.1.0"


[profile.dev]
opt-level = 1
